spring.application.name=BillingSfotware
resilience4j.ratelimiter.instances.allItem.limitForPeriod=5
resilience4j.ratelimiter.instances.allItem.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.allItem.timeoutDuration=1m
