spring.application.name=BillingSfotware
spring.data.mongodb.uri=mongodb+srv://rohpal3:Ronika%401998@cluster0.qfxsrbj.mongodb.net/BillingSoftware
resilience4j.ratelimiter.instances.allItem.limitForPeriod=5
resilience4j.ratelimiter.instances.allItem.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.allItem.timeoutDuration=1m