spring.application.name=BillingSfotware
spring.data.mongodb.uri=mongodb://localhost:27017/BillingSoftware
resilience4j.ratelimiter.instances.allItem.limitForPeriod=5
resilience4j.ratelimiter.instances.allItem.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.allItem.timeoutDuration=1m